/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppSusuRouteImport } from './routes/_authenticated/app.susu'
import { Route as AuthenticatedAppOrdersRouteImport } from './routes/_authenticated/app.orders'
import { Route as AuthenticatedAppMarketRouteImport } from './routes/_authenticated/app.market'
import { Route as AuthenticatedAppLoansRouteImport } from './routes/_authenticated/app.loans'
import { Route as AuthenticatedAppIncomeRouteImport } from './routes/_authenticated/app.income'
import { Route as AuthenticatedAppHistoryRouteImport } from './routes/_authenticated/app.history'
import { Route as AuthenticatedAppExpensesRouteImport } from './routes/_authenticated/app.expenses'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppSusuGroupIdRouteImport } from './routes/_authenticated/app.susu.$groupId'
import { Route as AuthenticatedAppMarketCartRouteImport } from './routes/_authenticated/app.market.cart'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSusuRoute = AuthenticatedAppSusuRouteImport.update({
  id: '/susu',
  path: '/susu',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOrdersRoute = AuthenticatedAppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMarketRoute = AuthenticatedAppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLoansRoute = AuthenticatedAppLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppIncomeRoute = AuthenticatedAppIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHistoryRoute = AuthenticatedAppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppExpensesRoute =
  AuthenticatedAppExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSusuGroupIdRoute =
  AuthenticatedAppSusuGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AuthenticatedAppSusuRoute,
  } as any)
const AuthenticatedAppMarketCartRoute =
  AuthenticatedAppMarketCartRouteImport.update({
    id: '/cart',
    path: '/cart',
    getParentRoute: () => AuthenticatedAppMarketRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/expenses': typeof AuthenticatedAppExpensesRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/income': typeof AuthenticatedAppIncomeRoute
  '/app/loans': typeof AuthenticatedAppLoansRoute
  '/app/market': typeof AuthenticatedAppMarketRouteWithChildren
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/susu': typeof AuthenticatedAppSusuRouteWithChildren
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/market/cart': typeof AuthenticatedAppMarketCartRoute
  '/app/susu/$groupId': typeof AuthenticatedAppSusuGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/expenses': typeof AuthenticatedAppExpensesRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/income': typeof AuthenticatedAppIncomeRoute
  '/app/loans': typeof AuthenticatedAppLoansRoute
  '/app/market': typeof AuthenticatedAppMarketRouteWithChildren
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/susu': typeof AuthenticatedAppSusuRouteWithChildren
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/market/cart': typeof AuthenticatedAppMarketCartRoute
  '/app/susu/$groupId': typeof AuthenticatedAppSusuGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/expenses': typeof AuthenticatedAppExpensesRoute
  '/_authenticated/app/history': typeof AuthenticatedAppHistoryRoute
  '/_authenticated/app/income': typeof AuthenticatedAppIncomeRoute
  '/_authenticated/app/loans': typeof AuthenticatedAppLoansRoute
  '/_authenticated/app/market': typeof AuthenticatedAppMarketRouteWithChildren
  '/_authenticated/app/orders': typeof AuthenticatedAppOrdersRoute
  '/_authenticated/app/susu': typeof AuthenticatedAppSusuRouteWithChildren
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/market/cart': typeof AuthenticatedAppMarketCartRoute
  '/_authenticated/app/susu/$groupId': typeof AuthenticatedAppSusuGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/admin'
    | '/app/expenses'
    | '/app/history'
    | '/app/income'
    | '/app/loans'
    | '/app/market'
    | '/app/orders'
    | '/app/susu'
    | '/app/'
    | '/app/market/cart'
    | '/app/susu/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/admin'
    | '/app/expenses'
    | '/app/history'
    | '/app/income'
    | '/app/loans'
    | '/app/market'
    | '/app/orders'
    | '/app/susu'
    | '/app'
    | '/app/market/cart'
    | '/app/susu/$groupId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/expenses'
    | '/_authenticated/app/history'
    | '/_authenticated/app/income'
    | '/_authenticated/app/loans'
    | '/_authenticated/app/market'
    | '/_authenticated/app/orders'
    | '/_authenticated/app/susu'
    | '/_authenticated/app/'
    | '/_authenticated/app/market/cart'
    | '/_authenticated/app/susu/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/susu': {
      id: '/_authenticated/app/susu'
      path: '/susu'
      fullPath: '/app/susu'
      preLoaderRoute: typeof AuthenticatedAppSusuRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/orders': {
      id: '/_authenticated/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AuthenticatedAppOrdersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/market': {
      id: '/_authenticated/app/market'
      path: '/market'
      fullPath: '/app/market'
      preLoaderRoute: typeof AuthenticatedAppMarketRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/loans': {
      id: '/_authenticated/app/loans'
      path: '/loans'
      fullPath: '/app/loans'
      preLoaderRoute: typeof AuthenticatedAppLoansRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/income': {
      id: '/_authenticated/app/income'
      path: '/income'
      fullPath: '/app/income'
      preLoaderRoute: typeof AuthenticatedAppIncomeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/history': {
      id: '/_authenticated/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AuthenticatedAppHistoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/expenses': {
      id: '/_authenticated/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AuthenticatedAppExpensesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/susu/$groupId': {
      id: '/_authenticated/app/susu/$groupId'
      path: '/$groupId'
      fullPath: '/app/susu/$groupId'
      preLoaderRoute: typeof AuthenticatedAppSusuGroupIdRouteImport
      parentRoute: typeof AuthenticatedAppSusuRoute
    }
    '/_authenticated/app/market/cart': {
      id: '/_authenticated/app/market/cart'
      path: '/cart'
      fullPath: '/app/market/cart'
      preLoaderRoute: typeof AuthenticatedAppMarketCartRouteImport
      parentRoute: typeof AuthenticatedAppMarketRoute
    }
  }
}

interface AuthenticatedAppMarketRouteChildren {
  AuthenticatedAppMarketCartRoute: typeof AuthenticatedAppMarketCartRoute
}

const AuthenticatedAppMarketRouteChildren: AuthenticatedAppMarketRouteChildren =
  {
    AuthenticatedAppMarketCartRoute: AuthenticatedAppMarketCartRoute,
  }

const AuthenticatedAppMarketRouteWithChildren =
  AuthenticatedAppMarketRoute._addFileChildren(
    AuthenticatedAppMarketRouteChildren,
  )

interface AuthenticatedAppSusuRouteChildren {
  AuthenticatedAppSusuGroupIdRoute: typeof AuthenticatedAppSusuGroupIdRoute
}

const AuthenticatedAppSusuRouteChildren: AuthenticatedAppSusuRouteChildren = {
  AuthenticatedAppSusuGroupIdRoute: AuthenticatedAppSusuGroupIdRoute,
}

const AuthenticatedAppSusuRouteWithChildren =
  AuthenticatedAppSusuRoute._addFileChildren(AuthenticatedAppSusuRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppExpensesRoute: typeof AuthenticatedAppExpensesRoute
  AuthenticatedAppHistoryRoute: typeof AuthenticatedAppHistoryRoute
  AuthenticatedAppIncomeRoute: typeof AuthenticatedAppIncomeRoute
  AuthenticatedAppLoansRoute: typeof AuthenticatedAppLoansRoute
  AuthenticatedAppMarketRoute: typeof AuthenticatedAppMarketRouteWithChildren
  AuthenticatedAppOrdersRoute: typeof AuthenticatedAppOrdersRoute
  AuthenticatedAppSusuRoute: typeof AuthenticatedAppSusuRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppExpensesRoute: AuthenticatedAppExpensesRoute,
  AuthenticatedAppHistoryRoute: AuthenticatedAppHistoryRoute,
  AuthenticatedAppIncomeRoute: AuthenticatedAppIncomeRoute,
  AuthenticatedAppLoansRoute: AuthenticatedAppLoansRoute,
  AuthenticatedAppMarketRoute: AuthenticatedAppMarketRouteWithChildren,
  AuthenticatedAppOrdersRoute: AuthenticatedAppOrdersRoute,
  AuthenticatedAppSusuRoute: AuthenticatedAppSusuRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
