/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDemoRouteImport } from './routes/_authenticated/demo'
import { Route as AuthenticatedDemoIndexRouteImport } from './routes/_authenticated/demo.index'
import { Route as AuthenticatedDemoSusuRouteImport } from './routes/_authenticated/demo.susu'
import { Route as AuthenticatedDemoMarketRouteImport } from './routes/_authenticated/demo.market'
import { Route as AuthenticatedDemoLoansRouteImport } from './routes/_authenticated/demo.loans'
import { Route as AuthenticatedDemoIncomeRouteImport } from './routes/_authenticated/demo.income'
import { Route as AuthenticatedDemoExpensesRouteImport } from './routes/_authenticated/demo.expenses'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDemoRoute = AuthenticatedDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemoIndexRoute = AuthenticatedDemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDemoRoute,
} as any)
const AuthenticatedDemoSusuRoute = AuthenticatedDemoSusuRouteImport.update({
  id: '/susu',
  path: '/susu',
  getParentRoute: () => AuthenticatedDemoRoute,
} as any)
const AuthenticatedDemoMarketRoute = AuthenticatedDemoMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedDemoRoute,
} as any)
const AuthenticatedDemoLoansRoute = AuthenticatedDemoLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthenticatedDemoRoute,
} as any)
const AuthenticatedDemoIncomeRoute = AuthenticatedDemoIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AuthenticatedDemoRoute,
} as any)
const AuthenticatedDemoExpensesRoute =
  AuthenticatedDemoExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedDemoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof AuthenticatedDemoRouteWithChildren
  '/demo/expenses': typeof AuthenticatedDemoExpensesRoute
  '/demo/income': typeof AuthenticatedDemoIncomeRoute
  '/demo/loans': typeof AuthenticatedDemoLoansRoute
  '/demo/market': typeof AuthenticatedDemoMarketRoute
  '/demo/susu': typeof AuthenticatedDemoSusuRoute
  '/demo/': typeof AuthenticatedDemoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo/expenses': typeof AuthenticatedDemoExpensesRoute
  '/demo/income': typeof AuthenticatedDemoIncomeRoute
  '/demo/loans': typeof AuthenticatedDemoLoansRoute
  '/demo/market': typeof AuthenticatedDemoMarketRoute
  '/demo/susu': typeof AuthenticatedDemoSusuRoute
  '/demo': typeof AuthenticatedDemoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/demo': typeof AuthenticatedDemoRouteWithChildren
  '/_authenticated/demo/expenses': typeof AuthenticatedDemoExpensesRoute
  '/_authenticated/demo/income': typeof AuthenticatedDemoIncomeRoute
  '/_authenticated/demo/loans': typeof AuthenticatedDemoLoansRoute
  '/_authenticated/demo/market': typeof AuthenticatedDemoMarketRoute
  '/_authenticated/demo/susu': typeof AuthenticatedDemoSusuRoute
  '/_authenticated/demo/': typeof AuthenticatedDemoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo'
    | '/demo/expenses'
    | '/demo/income'
    | '/demo/loans'
    | '/demo/market'
    | '/demo/susu'
    | '/demo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo/expenses'
    | '/demo/income'
    | '/demo/loans'
    | '/demo/market'
    | '/demo/susu'
    | '/demo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/demo'
    | '/_authenticated/demo/expenses'
    | '/_authenticated/demo/income'
    | '/_authenticated/demo/loans'
    | '/_authenticated/demo/market'
    | '/_authenticated/demo/susu'
    | '/_authenticated/demo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/demo': {
      id: '/_authenticated/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof AuthenticatedDemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/': {
      id: '/_authenticated/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof AuthenticatedDemoIndexRouteImport
      parentRoute: typeof AuthenticatedDemoRoute
    }
    '/_authenticated/demo/susu': {
      id: '/_authenticated/demo/susu'
      path: '/susu'
      fullPath: '/demo/susu'
      preLoaderRoute: typeof AuthenticatedDemoSusuRouteImport
      parentRoute: typeof AuthenticatedDemoRoute
    }
    '/_authenticated/demo/market': {
      id: '/_authenticated/demo/market'
      path: '/market'
      fullPath: '/demo/market'
      preLoaderRoute: typeof AuthenticatedDemoMarketRouteImport
      parentRoute: typeof AuthenticatedDemoRoute
    }
    '/_authenticated/demo/loans': {
      id: '/_authenticated/demo/loans'
      path: '/loans'
      fullPath: '/demo/loans'
      preLoaderRoute: typeof AuthenticatedDemoLoansRouteImport
      parentRoute: typeof AuthenticatedDemoRoute
    }
    '/_authenticated/demo/income': {
      id: '/_authenticated/demo/income'
      path: '/income'
      fullPath: '/demo/income'
      preLoaderRoute: typeof AuthenticatedDemoIncomeRouteImport
      parentRoute: typeof AuthenticatedDemoRoute
    }
    '/_authenticated/demo/expenses': {
      id: '/_authenticated/demo/expenses'
      path: '/expenses'
      fullPath: '/demo/expenses'
      preLoaderRoute: typeof AuthenticatedDemoExpensesRouteImport
      parentRoute: typeof AuthenticatedDemoRoute
    }
  }
}

interface AuthenticatedDemoRouteChildren {
  AuthenticatedDemoExpensesRoute: typeof AuthenticatedDemoExpensesRoute
  AuthenticatedDemoIncomeRoute: typeof AuthenticatedDemoIncomeRoute
  AuthenticatedDemoLoansRoute: typeof AuthenticatedDemoLoansRoute
  AuthenticatedDemoMarketRoute: typeof AuthenticatedDemoMarketRoute
  AuthenticatedDemoSusuRoute: typeof AuthenticatedDemoSusuRoute
  AuthenticatedDemoIndexRoute: typeof AuthenticatedDemoIndexRoute
}

const AuthenticatedDemoRouteChildren: AuthenticatedDemoRouteChildren = {
  AuthenticatedDemoExpensesRoute: AuthenticatedDemoExpensesRoute,
  AuthenticatedDemoIncomeRoute: AuthenticatedDemoIncomeRoute,
  AuthenticatedDemoLoansRoute: AuthenticatedDemoLoansRoute,
  AuthenticatedDemoMarketRoute: AuthenticatedDemoMarketRoute,
  AuthenticatedDemoSusuRoute: AuthenticatedDemoSusuRoute,
  AuthenticatedDemoIndexRoute: AuthenticatedDemoIndexRoute,
}

const AuthenticatedDemoRouteWithChildren =
  AuthenticatedDemoRoute._addFileChildren(AuthenticatedDemoRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDemoRoute: typeof AuthenticatedDemoRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDemoRoute: AuthenticatedDemoRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
