/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoSusuRouteImport } from './routes/demo.susu'
import { Route as DemoMarketRouteImport } from './routes/demo.market'
import { Route as DemoLoansRouteImport } from './routes/demo.loans'
import { Route as DemoIncomeRouteImport } from './routes/demo.income'
import { Route as DemoExpensesRouteImport } from './routes/demo.expenses'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoSusuRoute = DemoSusuRouteImport.update({
  id: '/susu',
  path: '/susu',
  getParentRoute: () => DemoRoute,
} as any)
const DemoMarketRoute = DemoMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => DemoRoute,
} as any)
const DemoLoansRoute = DemoLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => DemoRoute,
} as any)
const DemoIncomeRoute = DemoIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => DemoRoute,
} as any)
const DemoExpensesRoute = DemoExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => DemoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/expenses': typeof DemoExpensesRoute
  '/demo/income': typeof DemoIncomeRoute
  '/demo/loans': typeof DemoLoansRoute
  '/demo/market': typeof DemoMarketRoute
  '/demo/susu': typeof DemoSusuRoute
  '/demo/': typeof DemoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/expenses': typeof DemoExpensesRoute
  '/demo/income': typeof DemoIncomeRoute
  '/demo/loans': typeof DemoLoansRoute
  '/demo/market': typeof DemoMarketRoute
  '/demo/susu': typeof DemoSusuRoute
  '/demo': typeof DemoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/expenses': typeof DemoExpensesRoute
  '/demo/income': typeof DemoIncomeRoute
  '/demo/loans': typeof DemoLoansRoute
  '/demo/market': typeof DemoMarketRoute
  '/demo/susu': typeof DemoSusuRoute
  '/demo/': typeof DemoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/demo/expenses'
    | '/demo/income'
    | '/demo/loans'
    | '/demo/market'
    | '/demo/susu'
    | '/demo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/expenses'
    | '/demo/income'
    | '/demo/loans'
    | '/demo/market'
    | '/demo/susu'
    | '/demo'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/demo/expenses'
    | '/demo/income'
    | '/demo/loans'
    | '/demo/market'
    | '/demo/susu'
    | '/demo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/susu': {
      id: '/demo/susu'
      path: '/susu'
      fullPath: '/demo/susu'
      preLoaderRoute: typeof DemoSusuRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/market': {
      id: '/demo/market'
      path: '/market'
      fullPath: '/demo/market'
      preLoaderRoute: typeof DemoMarketRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/loans': {
      id: '/demo/loans'
      path: '/loans'
      fullPath: '/demo/loans'
      preLoaderRoute: typeof DemoLoansRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/income': {
      id: '/demo/income'
      path: '/income'
      fullPath: '/demo/income'
      preLoaderRoute: typeof DemoIncomeRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/expenses': {
      id: '/demo/expenses'
      path: '/expenses'
      fullPath: '/demo/expenses'
      preLoaderRoute: typeof DemoExpensesRouteImport
      parentRoute: typeof DemoRoute
    }
  }
}

interface DemoRouteChildren {
  DemoExpensesRoute: typeof DemoExpensesRoute
  DemoIncomeRoute: typeof DemoIncomeRoute
  DemoLoansRoute: typeof DemoLoansRoute
  DemoMarketRoute: typeof DemoMarketRoute
  DemoSusuRoute: typeof DemoSusuRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoExpensesRoute: DemoExpensesRoute,
  DemoIncomeRoute: DemoIncomeRoute,
  DemoLoansRoute: DemoLoansRoute,
  DemoMarketRoute: DemoMarketRoute,
  DemoSusuRoute: DemoSusuRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
